import 'dart:convert';

import 'ai_models.dart';

class AiRequest {
  final String text;
  final DateTime now;
  final String timezone;
  final String contextSummary;
  const AiRequest({
    required this.text,
    required this.now,
    required this.timezone,
    required this.contextSummary,
  });
}

class AiProviderException implements Exception {
  final String message;
  const AiProviderException(this.message);
  @override
  String toString() => message;
}

/// عقد مجرد — لا يربط التطبيق بمزوّد معين (مواصفة H، قاعدة 14/45).
abstract class AiService {
  String get providerName;
  Future<AiExtractionResult> extractEvents(AiRequest request);
  /// Phase 2: محادثة مع استدعاء أدوات (create/update/delete/search/getFreeSlots)
  Future<String> chat(String message);
}

const aiSchemaJson = '''
{
  "events": [
    {
      "title": "string (required)",
      "startDate": "YYYY-MM-DD (required)",
      "startTime": "HH:mm or null",
      "endDate": "YYYY-MM-DD",
      "endTime": "HH:mm or null",
      "category": "study|work|personal|university|exercise|meeting|important|other (required)",
      "description": "string",
      "location": "string",
      "isAllDay": "boolean (required)",
      "timeMissing": "boolean",
      "suggested": "boolean",
      "reminders": "array of integers — minutes before start, e.g. [10, 60]",
      "importance": "normal|important|critical"
    }
  ],
  "tasks": [
    {
      "title": "string (required)",
      "dueDate": "YYYY-MM-DD or null"
    }
  ],
  "ambiguities": ["string"]
}
''';

String buildSystemPrompt(AiRequest r) => '''
You are a scheduling extraction engine for a personal timeline app.
Today's date: ${r.now.toIso8601String()}
User timezone: ${r.timezone}
${r.contextSummary}

RULES:
1. You NEVER write to any database. You only return structured data.
2. You NEVER invent a time or date the user did not state or clearly imply.
   If time is missing, return "timeMissing": true — do not guess.
3. Resolve all relative dates ("tomorrow", "next Friday", "بكرة", "غدًا") against today's date above.
4. Supported categories: study, work, personal, university, exercise, meeting, important, other. If unclear, use "other".
5. If a time is generated by you (not stated), mark "suggested": true.
6. If input is ambiguous, return it in "ambiguities" — never resolve silently.
7. REMINDERS: only if the user explicitly asks (e.g. "ذكرني قبلها بـ10 دقائق", "remind me an hour before") → "reminders": [minutes before start]. Never invent reminders. The app automatically adds an at-start notification, so do NOT add 0.
8. IMPORTANCE: set "important" or "critical" ONLY if the user emphasizes it ("مهم جدًا", "حاسم", "لا يفوتني", "critical"). Otherwise "normal".
9. TASKS: todo items WITHOUT a specific clock time (shopping, studying a chapter, calls to make) go into "tasks" — not "events". If the item HAS a specific time, it is an event. dueDate only if the user stated a day; otherwise null.
10. Return ONLY valid JSON matching this schema — no prose, no markdown fences:
$aiSchemaJson
''';

String stripJsonFences(String s) {
  var t = s.trim();
  if (t.startsWith('```')) {
    t = t.replaceFirst(RegExp(r'^```[a-zA-Z]*\s*'), '');
    if (t.endsWith('```')) t = t.substring(0, t.length - 3);
  }
  final start = t.indexOf('{');
  final end = t.lastIndexOf('}');
  if (start >= 0 && end > start) return t.substring(start, end + 1);
  return t;
}

/// طبقة التحقق المشتركة (مواصفة H) — تعمل مع كل المزوّدين.
AiExtractionResult validateAiJson(String raw) {
  Map<String, dynamic> json;
  try {
    json = jsonDecode(stripJsonFences(raw)) as Map<String, dynamic>;
  } catch (_) {
    return AiExtractionResult(
        const [], ['AI returned invalid JSON — please try rephrasing.']);
  }

  final events = <ProposedEvent>[];
  final tasks = <ProposedTask>[];
  final ambiguities = <String>[
    ...(json['ambiguities'] as List? ?? const []).map((e) => '$e'),
  ];

  // ── الأحداث ──
  for (final item in (json['events'] as List? ?? const [])) {
    final m = item as Map<String, dynamic>;
    final title = m['title'] as String?;
    if (title == null || title.trim().isEmpty) {
      ambiguities.add('Skipped an event with no title.');
      continue;
    }
    DateTime? start = _parse(m['startDate'], m['startTime']);
    DateTime? end = _parse(m['endDate'] ?? m['startDate'], m['endTime']);
    final rawTime = m['startTime'];
    final timeMissing = (m['timeMissing'] as bool? ?? false) ||
        rawTime == null || '$rawTime'.trim().isEmpty || start == null;

    if (start != null && end != null && end.isBefore(start)) {
      end = start.add(const Duration(hours: 1));
      ambiguities.add('"$title": end before start — defaulted to 1 hour.');
    }

    final reminders = <int>{};
    for (final r in (m['reminders'] as List? ?? const [])) {
      final v = int.tryParse('$r');
      if (v != null && v > 0 && v <= 4320) reminders.add(v);
    }

    final imp = m['importance'] as String?;
    final String importance =
        (imp == 'important' || imp == 'critical') ? imp! : 'normal';

    events.add(ProposedEvent(
      title: title.trim(),
      start: start,
      end: end ?? start?.add(const Duration(hours: 1)),
      isAllDay: m['isAllDay'] as bool? ?? false,
      category: m['category'] as String? ?? 'other',
      description: m['description'] as String?,
      location: m['location'] as String?,
      timeMissing: timeMissing,
      suggested: m['suggested'] as bool? ?? false,
      reminders: reminders.toList()..sort(),
      importance: importance,
    ));
  }

  // ── المهام ──
  for (final item in (json['tasks'] as List? ?? const [])) {
    final m = item as Map<String, dynamic>;
    final title = m['title'] as String?;
    if (title == null || title.trim().isEmpty) continue;
    DateTime? due;
    try {
      final d =
          m['dueDate'] == null ? null : DateTime.parse('${m['dueDate']}');
      due = d == null ? null : DateTime(d.year, d.month, d.day);
    } catch (_) {
      due = null;
    }
    tasks.add(ProposedTask(title: title.trim(), dueDate: due));
  }

  return AiExtractionResult(events, ambiguities, tasks: tasks);
}

DateTime? _parse(Object? date, Object? time) {
  if (date == null) return null;
  try {
    return DateTime.parse('$date${time == null ? '' : ' $time'}'.trim());
  } catch (_) {
    return null;
  }
}
